const ELEMENTS = [
  { atomicNumber: 1, symbol: 'H', name: 'هيدروجين', category: 'غير فلز', state: 'غاز', mass: 1.008, electronegativity: 2.20, bonds: 1 },
  { atomicNumber: 2, symbol: 'He', name: 'هيليوم', category: 'غاز نبيل', state: 'غاز', mass: 4.0026, electronegativity: 0, bonds: 0 },
  { atomicNumber: 3, symbol: 'Li', name: 'ليثيوم', category: 'فلز قلوي', state: 'صلب', mass: 6.94, electronegativity: 0.98, bonds: 1 },
  { atomicNumber: 4, symbol: 'Be', name: 'بيريليوم', category: 'فلز قلوي ترابي', state: 'صلب', mass: 9.0122, electronegativity: 1.57, bonds: 2 },
  { atomicNumber: 5, symbol: 'B', name: 'بورون', category: 'لا فلز', state: 'صلب', mass: 10.81, electronegativity: 2.04, bonds: 3 },
  { atomicNumber: 6, symbol: 'C', name: 'كربون', category: 'لا فلز', state: 'صلب', mass: 12.011, electronegativity: 2.55, bonds: 4 },
  { atomicNumber: 7, symbol: 'N', name: 'نتروجين', category: 'لا فلز', state: 'غاز', mass: 14.007, electronegativity: 3.04, bonds: 3 },
  { atomicNumber: 8, symbol: 'O', name: 'أكسجين', category: 'لا فلز', state: 'غاز', mass: 15.999, electronegativity: 3.44, bonds: 2 },
  { atomicNumber: 9, symbol: 'F', name: 'فلور', category: 'هالوجين', state: 'غاز', mass: 18.998, electronegativity: 3.98, bonds: 1 },
  { atomicNumber: 10, symbol: 'Ne', name: 'نئون', category: 'غاز نبيل', state: 'غاز', mass: 20.180, electronegativity: 0, bonds: 0 },
  { atomicNumber: 11, symbol: 'Na', name: 'صوديوم', category: 'فلز قلوي', state: 'صلب', mass: 22.990, electronegativity: 0.93, bonds: 1 },
  { atomicNumber: 12, symbol: 'Mg', name: 'مغنيسيوم', category: 'فلز قلوي ترابي', state: 'صلب', mass: 24.305, electronegativity: 1.31, bonds: 2 },
  { atomicNumber: 13, symbol: 'Al', name: 'ألومنيوم', category: 'فلز', state: 'صلب', mass: 26.982, electronegativity: 1.61, bonds: 3 },
  { atomicNumber: 14, symbol: 'Si', name: 'سيليكون', category: 'لا فلز', state: 'صلب', mass: 28.085, electronegativity: 1.90, bonds: 4 },
  { atomicNumber: 15, symbol: 'P', name: 'فسفور', category: 'لا فلز', state: 'صلب', mass: 30.974, electronegativity: 2.19, bonds: 3 },
  { atomicNumber: 16, symbol: 'S', name: 'كبريت', category: 'لا فلز', state: 'صلب', mass: 32.06, electronegativity: 2.58, bonds: 2 },
  { atomicNumber: 17, symbol: 'Cl', name: 'كلور', category: 'هالوجين', state: 'غاز', mass: 35.45, electronegativity: 3.16, bonds: 1 },
  { atomicNumber: 18, symbol: 'Ar', name: 'أرغون', category: 'غاز نبيل', state: 'غاز', mass: 39.948, electronegativity: 0, bonds: 0 },
  { atomicNumber: 19, symbol: 'K', name: 'بوتاسيوم', category: 'فلز قلوي', state: 'صلب', mass: 39.098, electronegativity: 0.82, bonds: 1 },
  { atomicNumber: 20, symbol: 'Ca', name: 'كالسيوم', category: 'فلز قلوي ترابي', state: 'صلب', mass: 40.078, electronegativity: 1.00, bonds: 2 },
  { atomicNumber: 21, symbol: 'Sc', name: 'سكانديوم', category: 'فلز انتقالي', state: 'صلب', mass: 44.956, electronegativity: 1.36, bonds: 3 },
  { atomicNumber: 22, symbol: 'Ti', name: 'تيتانيوم', category: 'فلز انتقالي', state: 'صلب', mass: 47.867, electronegativity: 1.54, bonds: 4 },
  { atomicNumber: 23, symbol: 'V', name: 'فاناديوم', category: 'فلز انتقالي', state: 'صلب', mass: 50.942, electronegativity: 1.63, bonds: 5 },
  { atomicNumber: 24, symbol: 'Cr', name: 'كروم', category: 'فلز انتقالي', state: 'صلب', mass: 51.996, electronegativity: 1.66, bonds: 6 },
  { atomicNumber: 25, symbol: 'Mn', name: 'منغنيز', category: 'فلز انتقالي', state: 'صلب', mass: 54.938, electronegativity: 1.55, bonds: 7 },
  { atomicNumber: 26, symbol: 'Fe', name: 'حديد', category: 'فلز انتقالي', state: 'صلب', mass: 55.845, electronegativity: 1.83, bonds: 2 },
  { atomicNumber: 27, symbol: 'Co', name: 'كوبالت', category: 'فلز انتقالي', state: 'صلب', mass: 58.933, electronegativity: 1.88, bonds: 3 },
  { atomicNumber: 28, symbol: 'Ni', name: 'نيكل', category: 'فلز انتقالي', state: 'صلب', mass: 58.693, electronegativity: 1.91, bonds: 2 },
  { atomicNumber: 29, symbol: 'Cu', name: 'نحاس', category: 'فلز انتقالي', state: 'صلب', mass: 63.546, electronegativity: 1.90, bonds: 2 },
  { atomicNumber: 30, symbol: 'Zn', name: 'زنك', category: 'فلز انتقالي', state: 'صلب', mass: 65.38, electronegativity: 1.65, bonds: 2 },
  { atomicNumber: 31, symbol: 'Ga', name: 'غاليوم', category: 'فلز', state: 'صلب', mass: 69.723, electronegativity: 1.81, bonds: 3 },
  { atomicNumber: 32, symbol: 'Ge', name: 'جرمانيوم', category: 'لا فلز', state: 'صلب', mass: 72.630, electronegativity: 2.01, bonds: 4 },
  { atomicNumber: 33, symbol: 'As', name: 'زرنيخ', category: 'لا فلز', state: 'صلب', mass: 74.922, electronegativity: 2.18, bonds: 3 },
  { atomicNumber: 34, symbol: 'Se', name: 'سيلينيوم', category: 'لا فلز', state: 'صلب', mass: 78.971, electronegativity: 2.55, bonds: 2 },
  { atomicNumber: 35, symbol: 'Br', name: 'بروم', category: 'هالوجين', state: 'سائل', mass: 79.904, electronegativity: 2.96, bonds: 1 },
  { atomicNumber: 36, symbol: 'Kr', name: 'كريبتون', category: 'غاز نبيل', state: 'غاز', mass: 83.798, electronegativity: 3.00, bonds: 0 },
  { atomicNumber: 37, symbol: 'Rb', name: 'روبيديوم', category: 'فلز قلوي', state: 'صلب', mass: 85.468, electronegativity: 0.82, bonds: 1 },
  { atomicNumber: 38, symbol: 'Sr', name: 'سترونشيوم', category: 'فلز قلوي ترابي', state: 'صلب', mass: 87.62, electronegativity: 0.95, bonds: 2 },
  { atomicNumber: 39, symbol: 'Y', name: 'إتريوم', category: 'فلز انتقالي', state: 'صلب', mass: 88.906, electronegativity: 1.22, bonds: 3 },
  { atomicNumber: 40, symbol: 'Zr', name: 'زركونيوم', category: 'فلز انتقالي', state: 'صلب', mass: 91.224, electronegativity: 1.33, bonds: 4 },
  { atomicNumber: 41, symbol: 'Nb', name: 'نيوبياوم', category: 'فلز انتقالي', state: 'صلب', mass: 92.906, electronegativity: 1.6, bonds: 5 },
  { atomicNumber: 42, symbol: 'Mo', name: 'موليبدينوم', category: 'فلز انتقالي', state: 'صلب', mass: 95.95, electronegativity: 2.16, bonds: 6 },
  { atomicNumber: 43, symbol: 'Tc', name: 'تكنيتيوم', category: 'فلز انتقالي', state: 'صلب', mass: 98.0, electronegativity: 1.9, bonds: 7 },
  { atomicNumber: 44, symbol: 'Ru', name: 'روثينيوم', category: 'فلز انتقالي', state: 'صلب', mass: 101.07, electronegativity: 2.2, bonds: 8 },
  { atomicNumber: 45, symbol: 'Rh', name: 'روديوم', category: 'فلز انتقالي', state: 'صلب', mass: 102.91, electronegativity: 2.28, bonds: 3 },
  { atomicNumber: 46, symbol: 'Pd', name: 'بالاديوم', category: 'فلز انتقالي', state: 'صلب', mass: 106.42, electronegativity: 2.20, bonds: 2 },
  { atomicNumber: 47, symbol: 'Ag', name: 'فضة', category: 'فلز انتقالي', state: 'صلب', mass: 107.87, electronegativity: 1.93, bonds: 1 },
  { atomicNumber: 48, symbol: 'Cd', name: 'كادميوم', category: 'فلز انتقالي', state: 'صلب', mass: 112.41, electronegativity: 1.69, bonds: 2 },
  { atomicNumber: 49, symbol: 'In', name: 'إنديوم', category: 'فلز', state: 'صلب', mass: 114.82, electronegativity: 1.78, bonds: 3 },
  { atomicNumber: 50, symbol: 'Sn', name: 'قصدير', category: 'فلز', state: 'صلب', mass: 118.71, electronegativity: 1.96, bonds: 4 },
  { atomicNumber: 51, symbol: 'Sb', name: 'إنتيمون', category: 'لا فلز', state: 'صلب', mass: 121.76, electronegativity: 2.05, bonds: 3 },
  { atomicNumber: 52, symbol: 'Te', name: 'تيلوريوم', category: 'لا فلز', state: 'صلب', mass: 127.60, electronegativity: 2.1, bonds: 2 },
  { atomicNumber: 53, symbol: 'I', name: 'يود', category: 'هالوجين', state: 'صلب', mass: 126.90, electronegativity: 2.66, bonds: 1 },
  { atomicNumber: 54, symbol: 'Xe', name: 'زينون', category: 'غاز نبيل', state: 'غاز', mass: 131.29, electronegativity: 2.60, bonds: 0 },
  { atomicNumber: 55, symbol: 'Cs', name: 'سيزيوم', category: 'فلز قلوي', state: 'صلب', mass: 132.91, electronegativity: 0.79, bonds: 1 },
  { atomicNumber: 56, symbol: 'Ba', name: 'باريوم', category: 'فلز قلوي ترابي', state: 'صلب', mass: 137.33, electronegativity: 0.89, bonds: 2 },
  { atomicNumber: 57, symbol: 'La', name: 'لانثانوم', category: 'لانثانيدات', state: 'صلب', mass: 138.91, electronegativity: 1.10, bonds: 3 },
  { atomicNumber: 58, symbol: 'Ce', name: 'سيريوم', category: 'لانثانيدات', state: 'صلب', mass: 140.12, electronegativity: 1.12, bonds: 3 },
  { atomicNumber: 59, symbol: 'Pr', name: 'برسيوديميوم', category: 'لانثانيدات', state: 'صلب', mass: 140.91, electronegativity: 1.13, bonds: 3 },
  { atomicNumber: 60, symbol: 'Nd', name: 'نوديميوم', category: 'لانثانيدات', state: 'صلب', mass: 144.24, electronegativity: 1.14, bonds: 3 },
  { atomicNumber: 61, symbol: 'Pm', name: 'بروميثيوم', category: 'لانثانيدات', state: 'صلب', mass: 145, electronegativity: 1.13, bonds: 3 },
  { atomicNumber: 62, symbol: 'Sm', name: 'ساماريوم', category: 'لانثانيدات', state: 'صلب', mass: 150.36, electronegativity: 1.17, bonds: 3 },
  { atomicNumber: 63, symbol: 'Eu', name: 'أوروبيوم', category: 'لانثانيدات', state: 'صلب', mass: 151.96, electronegativity: 1.20, bonds: 3 },
  { atomicNumber: 64, symbol: 'Gd', name: 'غادولينيوم', category: 'لانثانيدات', state: 'صلب', mass: 157.25, electronegativity: 1.20, bonds: 3 },
  { atomicNumber: 65, symbol: 'Tb', name: 'تربيوم', category: 'لانثانيدات', state: 'صلب', mass: 158.93, electronegativity: 1.20, bonds: 3 },
  { atomicNumber: 66, symbol: 'Dy', name: 'ديسبروسيوم', category: 'لانثانيدات', state: 'صلب', mass: 162.50, electronegativity: 1.22, bonds: 3 },
  { atomicNumber: 67, symbol: 'Ho', name: 'هولميوم', category: 'لانثانيدات', state: 'صلب', mass: 164.93, electronegativity: 1.23, bonds: 3 },
  { atomicNumber: 68, symbol: 'Er', name: 'إربيوم', category: 'لانثانيدات', state: 'صلب', mass: 167.26, electronegativity: 1.24, bonds: 3 },
  { atomicNumber: 69, symbol: 'Tm', name: 'ثوليوم', category: 'لانثانيدات', state: 'صلب', mass: 168.93, electronegativity: 1.25, bonds: 3 },
  { atomicNumber: 70, symbol: 'Yb', name: 'إتيربيوم', category: 'لانثانيدات', state: 'صلب', mass: 173.05, electronegativity: 1.10, bonds: 3 },
  { atomicNumber: 71, symbol: 'Lu', name: 'لوتيشيوم', category: 'لانثانيدات', state: 'صلب', mass: 174.97, electronegativity: 1.27, bonds: 3 },
  { atomicNumber: 72, symbol: 'Hf', name: 'هافنيوم', category: 'فلز انتقالي', state: 'صلب', mass: 178.49, electronegativity: 1.3, bonds: 4 },
  { atomicNumber: 73, symbol: 'Ta', name: 'تنتاليوم', category: 'فلز انتقالي', state: 'صلب', mass: 180.95, electronegativity: 1.5, bonds: 5 },
  { atomicNumber: 74, symbol: 'W', name: 'تنجستن', category: 'فلز انتقالي', state: 'صلب', mass: 183.84, electronegativity: 2.36, bonds: 6 },
  { atomicNumber: 75, symbol: 'Re', name: 'رينيوم', category: 'فلز انتقالي', state: 'صلب', mass: 186.21, electronegativity: 1.9, bonds: 7 },
  { atomicNumber: 76, symbol: 'Os', name: 'أوزميوم', category: 'فلز انتقالي', state: 'صلب', mass: 190.23, electronegativity: 2.2, bonds: 8 },
  { atomicNumber: 77, symbol: 'Ir', name: 'إيريديوم', category: 'فلز انتقالي', state: 'صلب', mass: 192.22, electronegativity: 2.20, bonds: 3 },
  { atomicNumber: 78, symbol: 'Pt', name: 'بلاتين', category: 'فلز انتقالي', state: 'صلب', mass: 195.08, electronegativity: 2.28, bonds: 2 },
  { atomicNumber: 79, symbol: 'Au', name: 'ذهب', category: 'فلز انتقالي', state: 'صلب', mass: 196.97, electronegativity: 2.54, bonds: 3 },
  { atomicNumber: 80, symbol: 'Hg', name: 'زئبق', category: 'فلز انتقالي', state: 'سائل', mass: 200.59, electronegativity: 2.00, bonds: 2 },
  { atomicNumber: 81, symbol: 'Tl', name: 'ثاليوم', category: 'فلز', state: 'صلب', mass: 204.38, electronegativity: 1.62, bonds: 3 },
  { atomicNumber: 82, symbol: 'Pb', name: 'رصاص', category: 'فلز', state: 'صلب', mass: 207.2, electronegativity: 2.33, bonds: 4 },
  { atomicNumber: 83, symbol: 'Bi', name: 'بيزموث', category: 'فلز', state: 'صلب', mass: 208.98, electronegativity: 2.02, bonds: 3 },
  { atomicNumber: 84, symbol: 'Po', name: 'بولونيوم', category: 'لا فلز', state: 'صلب', mass: 209.0, electronegativity: 2.0, bonds: 2 },
  { atomicNumber: 85, symbol: 'At', name: 'أستاتين', category: 'هالوجين', state: 'صلب', mass: 210.0, electronegativity: 2.2, bonds: 1 },
  { atomicNumber: 86, symbol: 'Rn', name: 'رادون', category: 'غاز نبيل', state: 'غاز', mass: 222.0, electronegativity: 0, bonds: 0 },
  { atomicNumber: 87, symbol: 'Fr', name: 'فرانسيوم', category: 'فلز قلوي', state: 'صلب', mass: 223.0, electronegativity: 0.7, bonds: 1 },
  { atomicNumber: 88, symbol: 'Ra', name: 'راديوم', category: 'فلز قلوي ترابي', state: 'صلب', mass: 226.0, electronegativity: 0.9, bonds: 2 },
  { atomicNumber: 89, symbol: 'Ac', name: 'أكتينيوم', category: 'أكتينيدات', state: 'صلب', mass: 227.0, electronegativity: 1.1, bonds: 3 },
  { atomicNumber: 90, symbol: 'Th', name: 'ثوريوم', category: 'أكتينيدات', state: 'صلب', mass: 232.04, electronegativity: 1.3, bonds: 4 },
  { atomicNumber: 91, symbol: 'Pa', name: 'بروميثيوم', category: 'أكتينيدات', state: 'صلب', mass: 231.04, electronegativity: 1.5, bonds: 5 },
  { atomicNumber: 92, symbol: 'U', name: 'يورانيوم', category: 'أكتينيدات', state: 'صلب', mass: 238.03, electronegativity: 1.38, bonds: 6 },
  { atomicNumber: 93, symbol: 'Np', name: 'نبتونيوم', category: 'أكتينيدات', state: 'صلب', mass: 237.0, electronegativity: 1.36, bonds: 5 },
  { atomicNumber: 94, symbol: 'Pu', name: 'بلوتونيوم', category: 'أكتينيدات', state: 'صلب', mass: 244.06, electronegativity: 1.28, bonds: 6 },
  { atomicNumber: 95, symbol: 'Am', name: 'أمريسيوم', category: 'أكتينيدات', state: 'صلب', mass: 243.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 96, symbol: 'Cm', name: 'كوريوم', category: 'أكتينيدات', state: 'صلب', mass: 247.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 97, symbol: 'Bk', name: 'بركيليوم', category: 'أكتينيدات', state: 'صلب', mass: 247.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 98, symbol: 'Cf', name: 'كالي فورنيوم', category: 'أكتينيدات', state: 'صلب', mass: 251.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 99, symbol: 'Es', name: 'أينشتينيوم', category: 'أكتينيدات', state: 'صلب', mass: 252.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 100, symbol: 'Fm', name: 'فيرميوم', category: 'أكتينيدات', state: 'صلب', mass: 257.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 101, symbol: 'Md', name: 'مندليفيوم', category: 'أكتينيدات', state: 'صلب', mass: 258.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 102, symbol: 'No', name: 'نوبليوم', category: 'أكتينيدات', state: 'صلب', mass: 259.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 103, symbol: 'Lr', name: 'لورنسيوم', category: 'أكتينيدات', state: 'صلب', mass: 266.0, electronegativity: 1.3, bonds: 3 },
  { atomicNumber: 104, symbol: 'Rf', name: 'رذرفورديوم', category: 'فلز انتقالي', state: 'صلب', mass: 267.0, electronegativity: 0, bonds: 4 },
  { atomicNumber: 105, symbol: 'Db', name: 'دبنيوم', category: 'فلز انتقالي', state: 'صلب', mass: 270.0, electronegativity: 0, bonds: 5 },
  { atomicNumber: 106, symbol: 'Sg', name: 'سيبورغيوم', category: 'فلز انتقالي', state: 'صلب', mass: 271.0, electronegativity: 0, bonds: 6 },
  { atomicNumber: 107, symbol: 'Bh', name: 'بوهريوم', category: 'فلز انتقالي', state: 'صلب', mass: 270.0, electronegativity: 0, bonds: 7 },
  { atomicNumber: 108, symbol: 'Hs', name: 'هسنيوم', category: 'فلز انتقالي', state: 'صلب', mass: 277.0, electronegativity: 0, bonds: 8 },
  { atomicNumber: 109, symbol: 'Mt', name: 'مايتيوريم', category: 'فلز انتقالي', state: 'صلب', mass: 278.0, electronegativity: 0, bonds: 3 },
  { atomicNumber: 110, symbol: 'Ds', name: 'دارمشتاتيوم', category: 'فلز انتقالي', state: 'صلب', mass: 281.0, electronegativity: 0, bonds: 2 },
  { atomicNumber: 111, symbol: 'Rg', name: 'رونتجينيوم', category: 'فلز انتقالي', state: 'صلب', mass: 282.0, electronegativity: 0, bonds: 3 },
  { atomicNumber: 112, symbol: 'Cn', name: 'كوبرنيكتيوم', category: 'فلز انتقالي', state: 'صلب', mass: 285.0, electronegativity: 0, bonds: 2 },
  { atomicNumber: 113, symbol: 'Nh', name: 'نيهونيوم', category: 'فلز', state: 'صلب', mass: 286.0, electronegativity: 0, bonds: 3 },
  { atomicNumber: 114, symbol: 'Fl', name: 'فليروفيوم', category: 'فلز', state: 'صلب', mass: 289.0, electronegativity: 0, bonds: 2 },
  { atomicNumber: 115, symbol: 'Mc', name: 'موسكوفيوم', category: 'لا فلز', state: 'صلب', mass: 290.0, electronegativity: 0, bonds: 3 },
  { atomicNumber: 116, symbol: 'Lv', name: 'ليفرموريوم', category: 'لا فلز', state: 'صلب', mass: 293.0, electronegativity: 0, bonds: 2 },
  { atomicNumber: 117, symbol: 'Ts', name: 'تينيسين', category: 'هالوجين', state: 'صلب', mass: 294.0, electronegativity: 2.0, bonds: 1 },
  { atomicNumber: 118, symbol: 'Og', name: 'أوغانيسون', category: 'غاز نبيل', state: 'غاز', mass: 294.0, electronegativity: 0, bonds: 0 }
];

window.ELEMENTS = ELEMENTS;

window.getElementByAtomicNumber = function (atomicNumber) {
  return ELEMENTS.find((element) => element.atomicNumber === Number(atomicNumber)) || null;
};

window.getElementBySymbol = function (symbol) {
  return ELEMENTS.find((element) => element.symbol.toLowerCase() === String(symbol).toLowerCase()) || null;
};
